### ISSUE TITLE
Iets meer uitleg bij figuur 3.1 

### ISSUE THREAD

**Issue by MichelGrothe** [Geonovum/raamwerk-geostandaarden-4.0#16]
Ik zou graag iets meer duiding zien bij figuur 3.1.  Korte uitleg over wat het betekent dat NEN3610 "imports" vanuit MIM, OGC, ISO en INSPIRE GCM en W3C.

**Comment by PalmJanssen** [comment]
korte duiding in https://github.com/Geonovum/raamwerk-geostandaarden/pull/20
